export const ACTION_TYPES = {
  SITE_PUBLISH: {
    GET_OPTIONS: 'GET_SITE_PUBLISH_OPTIONS',
    SET_OPTIONS: 'SET_SITE_PUBLISH_OPTIONS',
    POST_OPTIONS_TO_DB: 'POST_SITE_PUBLISH_OPTIONS_TO_DB',
    CHANGE_GLOBAL_STATE: 'CHANGE_SITE_PUBLISH_OPTIONS_GLOBAL_STATE',
  },

  OTHER_SETTINGS: {
    SET_PAYMENT_POINTER: 'SET_PAYMENT_POINTER',
    GET_PAYMENT_POINTER: 'GET_PAYMENT_POINTER',
    POST_PAYMENT_POINTER: 'POST_PAYMENT_POINTER',
    CHANGE_PAYMENT_POINTER_GLOBAL_STATE: 'CHANGE_PAYMENT_POINTER_GLOBAL_STATE',
  },

  SITE_LIKER_INFO: {
    GET_INFO: 'GET_SITE_LIKER_INFO',
    SET_INFO: 'SET_SITE_LIKER_INFO',
    POST_INFO_TO_DB: 'POST_SITE_LIKER_INFO_TO_DB',
    CHANGE_GLOBAL_STATE: 'CHANGE_SITE_LIKER_INFO_GLOBAL_STATE',
    SET_FORBIDDEN_ERROR: 'SET_FORBIDDEN_ERROR',
  },

  USER_LIKER_INFO: {
    GET_INFO: 'GET_USER_LIKER_INFO',
    SET_INFO: 'SET_USER_LIKER_INFO',
    POST_INFO_TO_DB: 'POST_USER_LIKER_INFO_TO_DB',
    CHANGE_GLOBAL_STATE: 'CHANGE_USER_LIKER_INFO_GLOBAL_STATE',
  },

  COMMON: {
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  },
};

export const API_ENDPOINTS = {
  SITE_PUBLISH: '/likecoin/v1/option/publish',
  WEB_MONETIZATION: '/likecoin/v1/option/web-monetization',
  SITE_LIKER_INFO: '/likecoin/v1/options/liker-id',
  USER_LIKER_INFO: '/likecoin/v1/options/liker-id/user',
};

export const STORE_NAMES = {
  SITE_PUBLISH: 'likecoin/site_publish',
  OTHER_SETTINGS: 'likecoin/other_settings',
  SITE_LIKER_INFO: 'likecoin/site_liker_info',
  USER_LIKER_INFO: 'likecoin/user_liker_info',
};
